baseurl = "http://fullstopeditorial.ca"
languageCode = "en-us"
title = "Full Stop Editorial"
theme = ""
publishDir = "docs"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Full Stop Editorial"
	description = "Full Stop Editorial located in Toronto, Ontario. Offering copywriting, editing, marketing copy, reports, newsletters, social media, layout and consulting services."


	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		logo = "logo-01.png"	

	[params.about]

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "We’ll work with your budget. Let’s talk."
		
		email = "jcrljen@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "What We Do"
	url  = "/#about"
	weight = 10

[[menu.main]]
	name = "Recent Projects"
	URL  = "/#recent"
	weight = 11

[[menu.main]]
	name = "Get In Touch"
	URL  = "/#contact"
	weight = 0
